class DataUdang {

  // ================= DATA HARGA =================
  static List<Map<String, String>> hargaUdang = [
    {
      // ===== 03/01/2026 =====
      'No': '1',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '20',
      'Harga/Kg': '189000',
      'Tanggal Restock':'05/01/2026',
      'Kode_Peti': 'A',
      'Inbound' : '11.30',
      'Stok/Kg' :'87',
      'Outbound' :'14.10',
      'Status' :'-',
    },
    {
      'No': '2',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '20',
      'Harga/Kg': '189000',
      'Tanggal Restock':'07/01/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.30',
      'Stok/Kg' :'105',
      'Outbound' :'11.10',
      'Status' :'-',
    },
    {
      'No': '3',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '20',
      'Harga/Kg': '189000',
      'Tanggal Restock':'10/01/2026',
      'Kode_Peti': 'A',
      'Inbound' : '11.30',
      'Stok/Kg' :'63',
      'Outbound' :'14.10',
      'Status' :'-',
    },
    { 
      'No': '4',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '25',
      'Harga/Kg': '152000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '5',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '30',
      'Harga/Kg': 'Rp.141000',
      'Tanggal Restock':'07/01/2026',
      'Kode_Peti': 'B',
      'Inbound' : '09.30',
      'Stok/Kg' :'63',
      'Outbound' :'11.10',
      'Status' :'-',
    },
    {
      'No': '6',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '30',
      'Harga/Kg': 'Rp.141000',
      'Tanggal Restock':'10/01/2026',
      'Kode_Peti': 'A',
      'Inbound' : '11.30',
      'Stok/Kg' :'112',
      'Outbound' :'14.10',
      'Status' :'-',
    },
    {
      'No': '7',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '30',
      'Harga/Kg': 'Rp.141000',
      'Tanggal Restock':'14/01/2026',
      'Kode_Peti': 'A',
      'Inbound' : '08.30',
      'Stok/Kg' :'75',
      'Outbound' :'11.10',
      'Status' :'-',
    },
    {
      'No': '8',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '30',
      'Harga/Kg': 'Rp.141000',
      'Tanggal Restock':'26/01/2026',
      'Kode_Peti': 'A',
      'Inbound' : '10.30',
      'Stok/Kg' :'157',
      'Outbound' :'13.10',
      'Status' :'-',
    },
    {
      'No': '9',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '35',
      'Harga/Kg': 'Rp.130000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '10',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '40',
      'Harga/Kg': 'Rp.119000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '11',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '45',
      'Harga/Kg': 'Rp.106000',
      'Tanggal Restock':'06/01/2026',
      'Kode_Peti': 'A',
      'Inbound' : '08.30',
      'Stok/Kg' :'117',
      'Outbound' :'11.20',
      'Status' :'-',
    },
    {
      'No': '12',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '45',
      'Harga/Kg': 'Rp.106000',
      'Tanggal Restock':'26/01/2026',
      'Kode_Peti': 'C',
      'Inbound' : '10.30',
      'Stok/Kg' :'47',
      'Outbound' :'13.20',
      'Status' :'-',
    },
    {
      'No': '13',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '50',
      'Harga/Kg': 'Rp.97000',
      'Tanggal Restock':'26/01/2026',
      'Kode_Peti': 'B',
      'Inbound' : '10.30',
      'Stok/Kg' :'250',
      'Outbound' :'13.00',
      'Status' :'-',
    },
    {
      'No': '14',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '55',
      'Harga/Kg': 'Rp.84000',
      'Tanggal Restock':'14/01/2026',
      'Kode_Peti': 'B',
      'Inbound' : '08.30',
      'Stok/Kg' :'89',
      'Outbound' :'11. 10',
      'Status' :'-',
    },
    {
      'No': '15',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '55',
      'Harga/Kg': 'Rp.84000',
      'Tanggal Restock':'19/01/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.00',
      'Stok/Kg' :'109',
      'Outbound' :'11.45',
      'Status' :'-',
    },
    {
      'No': '16',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '60',
      'Harga/Kg': 'Rp.74000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '17',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '65',
      'Harga/Kg': 'Rp.64000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '18',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '70',
      'Harga/Kg': 'Rp.62000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '19',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '75',
      'Harga/Kg': 'Rp.58000',
      'Tanggal Restock':'16/01/2026',
      'Kode_Peti': 'A',
      'Inbound' : '11.30',
      'Stok/Kg' :'90',
      'Outbound' :'14.15',
      'Status' :'-',
    },
    {
      'No': '20',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '80',
      'Harga/Kg': 'Rp.56000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '21',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '85',
      'Harga/Kg': 'Rp.54000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '22',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '90',
      'Harga/Kg': 'Rp.51000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '23',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '95',
      'Harga/Kg': 'Rp.47000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '24',
      'Tanggal Update Harga': '03/01/2026',
      'Size': '100',
      'Harga/Kg': 'Rp.44000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      // ===== 05/02/2026 =====
      'No': '25',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '20',
      'Harga/Kg': 'Rp.191000',
      'Tanggal Restock':'06/02/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.30',
      'Stok/Kg' :'83',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '26',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '25',
      'Harga/Kg': 'Rp.165000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '27',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '30',
      'Harga/Kg': 'Rp.160000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '28',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '35',
      'Harga/Kg': 'Rp.145000',
      'Tanggal Restock':'21/02/2026',
      'Kode_Peti': 'A',
      'Inbound' : '14.30',
      'Stok/Kg' :'82',
      'Outbound' :'15.45',
      'Status' :'-',
    },
    {
      'No': '29',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '40',
      'Harga/Kg': 'Rp.135000',
      'Tanggal Restock':'06/02/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.35',
      'Stok/Kg' :'127',
      'Outbound' :'11.45',
      'Status' :'-',
    },
    {
      'No': '30',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '40',
      'Harga/Kg': 'Rp.135000',
      'Tanggal Restock':'27/02/2026',
      'Kode_Peti': 'A',
      'Inbound' : '08.15',
      'Stok/Kg' :'152',
      'Outbound' :'10.05',
      'Status' :'-',
    },
    {
      'No': '31',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '45',
      'Harga/Kg': 'Rp.120000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '32',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '50',
      'Harga/Kg': 'Rp.110000',
      'Tanggal Restock':'10/02/2026',
      'Kode_Peti': 'A',
      'Inbound' : '07.30',
      'Stok/Kg' :'77',
      'Outbound' :'10.00',
      'Status' :'-',
    },
    {
      'No': '33',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '50',
      'Harga/Kg': 'Rp.110000',
      'Tanggal Restock':'15/02/2026',
      'Kode_Peti': 'A',
      'Inbound' : '11.30',
      'Stok/Kg' :'115',
      'Outbound' :'13.00',
      'Status' :'-',
    },
    {
      'No': '34',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '55',
      'Harga/Kg': 'Rp.95000',
      'Tanggal Restock':'10/02/2026',
      'Kode_Peti': 'B',
      'Inbound' : '09.30',
      'Stok/Kg' :'69',
      'Outbound' :'10.00',
      'Status' :'-',
    },
    {
      'No': '35',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '60',
      'Harga/Kg': 'Rp.85000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '36',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '65',
      'Harga/Kg': 'Rp.73000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '37',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '70',
      'Harga/Kg': 'Rp.70000',
      'Tanggal Restock':'26/02/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.30',
      'Stok/Kg' :'45',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '38',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '75',
      'Harga/Kg': 'Rp.67000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '39',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '80',
      'Harga/Kg': 'Rp.65000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '40',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '85',
      'Harga/Kg': 'Rp.62000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '41',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '90',
      'Harga/Kg': 'Rp.57000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '42',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '95',
      'Harga/Kg': 'Rp.52000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '43',
      'Tanggal Update Harga': '05/02/2026',
      'Size': '100',
      'Harga/Kg': 'Rp.54000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      // ===== 02/03/2026 =====
      'No': '44',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '20',
      'Harga/Kg': 'Rp.200000',
      'Tanggal Restock':'14/03/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.30',
      'Stok/Kg' :'55',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '45',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '25',
      'Harga/Kg': 'Rp.162000',
      'Tanggal Restock':'19/03/2026',
      'Kode_Peti': 'A',
      'Inbound' : '07.55',
      'Stok/Kg' :'80',
      'Outbound' :'10.00',
      'Status' :'-',
    },
    {
      'No': '46',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '30',
      'Harga/Kg': 'Rp.152000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '47',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '35',
      'Harga/Kg': 'Rp.142000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'status' :'-',
    },
    {
      'No': '48',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '40',
      'Harga/Kg': 'Rp.131000',
      'Tanggal Restock':'02/03/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.30',
      'Stok/Kg' :'67',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '49',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '40',
      'Harga/Kg': 'Rp.131000',
      'Tanggal Restock':'07/03/2026',
      'Kode_Peti': 'A',
      'Inbound' : '12.30',
      'Stok/Kg' :'112',
      'Outbound' :'14.05',
      'Status' :'-',
    },
    {
      'No': '50',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '40',
      'Harga/Kg': 'Rp.131000',
      'Tanggal Restock':'18/03/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.30',
      'Stok/Kg' :'70',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '51',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '40',
      'Harga/Kg': 'Rp.131000',
      'Tanggal Restock':'18/03/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.30',
      'Stok/Kg' :'25',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '52',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '45',
      'Harga/Kg': 'Rp.118000',
      'Tanggal Restock':'27/03/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.30',
      'Stok/Kg' :'112',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '53',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '50',
      'Harga/Kg': 'Rp.108000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '54',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '55',
      'Harga/Kg': 'Rp.92000',
      'Tanggal Restock':'02/03/2026',
      'Kode_Peti': 'C',
      'Inbound' : '09.30',
      'Stok/Kg' :'47',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '55',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '55',
      'Harga/Kg': 'Rp.92000',
      'Tanggal Restock':'27/03/2026',
      'Kode_Peti': 'C',
      'Inbound' : '09.30',
      'Stok/Kg' :'97',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '56',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '60',
      'Harga/Kg': 'Rp.83000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '57',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '65',
      'Harga/Kg': 'Rp.68000',
      'Tanggal Restock':'02/03/2026',
      'Kode_Peti': 'B',
      'Inbound' : '09.30',
      'Stok/Kg' :'30',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '58',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '70',
      'Harga/Kg': 'Rp.66000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '59',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '75',
      'Harga/Kg': 'Rp.64000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '60',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '80',
      'Harga/Kg': 'Rp.62000',
      'Tanggal Restock':'29/03/2026',
      'Kode_Peti': 'A',
      'Inbound' :'12.30',
      'Stok/Kg' :'69',
      'Outbound' :'14.00',
      'Status' :'-',
    },
    {
      'No': '61',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '85',
      'Harga/Kg': 'Rp.60000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '62',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '90',
      'Harga/Kg': 'Rp.58000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '63',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '95',
      'Harga/Kg': 'Rp.56000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '64',
      'Tanggal Update Harga': '02/03/2026',
      'Size': '100',
      'Harga/Kg': 'Rp.55000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      // ===== 04/04/2026 =====
      'No': '65',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '20',
      'Harga/Kg': 'Rp.210000',
      'Tanggal Restock':'24/04/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.30',
      'Stok/Kg' :'52',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '66',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '25',
      'Harga/Kg': 'Rp.165000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '67',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '30',
      'Harga/Kg': 'Rp.160000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '68',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '35',
      'Harga/Kg': 'Rp.145000',
      'Tanggal Restock':'04/04/2026',
      'Kode_Peti': 'A',
      'Inbound' : '09.30',
      'Stok/Kg' :'83',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '69',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '35',
      'Harga/Kg': 'Rp.145000',
      'Tanggal Restock':'14/04/2026',
      'Kode_Peti': 'A',
      'Inbound' :'09.30',
      'Stok/Kg' :'72',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '70',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '35',
      'Harga/Kg': 'Rp.145000',
      'Tanggal Restock':'17/04/2026',
      'Kode_Peti': 'A',
      'Inbound' : '08.40',
      'Stok/Kg' :'46',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '71',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '40',
      'Harga/Kg': 'Rp.135000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '72',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '45',
      'Harga/Kg': 'Rp.120000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '73',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '50',
      'Harga/Kg': 'Rp.110000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '74',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '55',
      'Harga/Kg': 'Rp.95000',
      'Tanggal Restock':'17/04/2026',
      'Kode_Peti': 'B',
      'Inbound' : '08.40',
      'Stok/Kg' :'81',
      'Outbound' :'11.00',
      'Status' :'-',
    },
    {
      'No': '75',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '60',
      'Harga/Kg': 'Rp.85000',
      'Tanggal Restock':'10/04/2026',
      'Kode_Peti': 'A',
      'Inbound' : '11.10',
      'Stok/Kg' :'117',
      'Outbound' :'13.40',
      'Status' :'-',
    },
    {
      'No': '76',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '65',
      'Harga/Kg': 'Rp.73000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '77',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '70',
      'Harga/Kg': 'Rp.70000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '78',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '75',
      'Harga/Kg': 'Rp.67000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '79',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '80',
      'Harga/Kg': 'Rp.65000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '80',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '85',
      'Harga/Kg': 'Rp.62000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '81',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '90',
      'Harga/Kg': 'Rp.58000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '82',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '95',
      'Harga/Kg': 'Rp.56000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
    {
      'No': '83',
      'Tanggal Update Harga': '04/04/2026',
      'Size': '100',
      'Harga/Kg': 'Rp.54000',
      'Tanggal Restock':'-',
      'Kode_Peti': '-',
      'Inbound' : '-',
      'Stok/Kg' :'-',
      'Outbound' :'-',
      'Status' :'-',
    },
  ];
  // ================= DATA PETI =================
  static List<Map<String, String>> dataPeti = [
    {
      'Tanggal Restock': '05/01/2026',
      'Kode_Peti': 'A',
      'Size': '20',
      'Inbound': '11.30',
      'Outbound': '14.10',
      'Stok/Kg': '87',
    },
    {  
      'Tanggal Restock': '06/01/2026',
      'Kode_Peti': 'A',
      'Size': '45',
      'Inbound': '08.30',
      'Outbound': '11.20',
      'Stok/Kg': '117',
    },
    { 
      'Tanggal Restock': '07/01/2026',
      'Kode_Peti': 'A',
      'Size': '20',
      'Inbound': '1130',
      'Outbound': '14.10',
      'Stok/Kg': '87',
    },
    { 
      'Tanggal Restock': '07/01/2026',
      'Kode_Peti': 'B',
      'Size': '30',
      'Inbound': '11.30',
      'Outbound': '14.10',
      'Stok/Kg': '63',
    },
    { 
      'Tanggal Restock': '10/01/2026',
      'Kode_Peti': 'A',
      'Size': '30',
      'Inbound': '11.30',
      'Outbound': '14.10',
      'Stok/Kg': '112',
    },
    { 
      'Tanggal Restock': '14/01/2026',
      'Kode_Peti': 'A',
      'Size': '30',
      'Inbound': '08.30',
      'Outbound': '11.10',
      'Stok/Kg': '75',
    },
    { 
      'Tanggal Restock': '14/01/2026',
      'Kode_Peti': 'B',
      'Size': '55',
      'Inbound': '08.30',
      'Outbound': '11.10',
      'Stok/Kg': '89',
      },
    { 
      'Tanggal Restock': '16/01/2026',
      'Kode_Peti': 'A',
      'Size': '75',
      'Inbound': '11.30',
      'Outbound': '14.10',
      'Stok/Kg': '90',
      
    },
    {
      'Tanggal Restock': '19/01/2026',
      'Kode_Peti': 'A',
      'Size': '55',
      'Inbound': '09.00',
      'Outbound': '11.45:',
      'Stok/Kg': '109',
    },
    {
      
      'Tanggal Restock': '26/01/2026',
      'Kode_Peti': 'A',
      'Size': '45',
      'Inbound': '10.30',
      'Outbound': '13.00',
      'Stok/Kg': '47',
    },
    {
      'Tanggal Restock': '26/01/2026',
      'Kode_Peti': 'B',
      'Size': '50',
      'Inbound': '10.30',
      'Outbound': '13.00',
      'Stok/Kg': '250',
    },
    {
      'Tanggal Restock': '26/01/2026',
      'Kode_Peti': 'C',
      'Size': '45',
      'Inbound': '10.30',
      'Outbound': '13.00',
      'Stok/Kg': '30',
    },
    {
      'Tanggal Restock': '06/02/2026',
      'Kode_Peti': 'A',
      'Size': '40',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '101',
    },
    {
      'Tanggal Restock': '06/02/2026',
      'Kode_Peti': 'A',
      'Size': '20',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '35',
    },
    {
      'Tanggal Restock': '10/02/2026',
      'Kode_Peti': 'A',
      'Size': '50',
      'Inbound': '07.30',
      'Outbound': '10.00',
      'Stok/Kg': '75',
    },
    {
      'Tanggal Restock': '10/02/2026',
      'Kode_Peti': 'B',
      'Size': '55',
      'Inbound': '09.30',
      'Outbound':'11.00',
      'Stok/Kg': '69',
    },
    {
      'Tanggal Restock': '15/02/2026',
      'Kode_Peti': 'A',
      'Size': '50',
      'Inbound': '11.30',
      'Outbound':'13.00',
      'Stok/Kg': '115',
    },
    {
      'Tanggal Restock': '21/02/2026',
      'Kode_Peti': 'A',
      'Size': '35',
      'Inbound': '14.30',
      'Outbound':'15.45',
      'Stok/Kg': '82',
    },
    {
      'Tanggal Restock': '26/02/2026',
      'Kode_Peti': 'A',
      'Size': '70',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '45',
    },
    {
      'Tanggal Restock': '27/02/2026',
      'Kode_Peti': 'A',
      'Size': '40',
      'Inbound': '08.14',
      'Outbound': '10.05',
      'Stok/Kg': '152',
    },
    {
      'Tanggal Restock': '02/03/2026',
      'Kode_Peti': 'A',
      'Size': '40',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '67',
    },
    {
      'Tanggal Restock': '02/03/2026',
      'Kode_Peti': 'B',
      'Size': '65',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '30',
    },
    {
      'Tanggal Restock': '02/03/2026',
      'Kode_Peti': 'C',
      'Size': '55',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '47',
    },
    {
      'Tanggal Restock': '07/03/2026',
      'Kode_Peti': 'A',
      'Size': '40',
      'Inbound': '12.30',
      'Outbound': '14.05',
      'Stok/Kg': '112',
    },
    {
      'Tanggal Restock': '14/02/2026',
      'Kode_Peti': 'A',
      'Size': '20',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '55',
    },
    {
      'Tanggal Restock': '18/03/2026',
      'Kode_Peti': 'A',
      'Size': '40',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '70',
    },
    {
      'Tanggal Restock': '19/03/2026',
      'Kode_Peti': 'A',
      'Size': '25',
      'Inbound': '07.55',
      'Outbound': '10.00',
      'Stok/Kg': '80',
    },
    {
      'Tanggal Restock': '27/03/2026',
      'Kode_Peti': 'A',
      'Size': '45',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '112',
    },
    {
      'Tanggal Restock': '27/03/2026',
      'Kode_Peti': 'B',
      'Size': '40',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '25',
    },
    {
      'Tanggal Restock': '27/03/2026',
      'Kode_Peti': 'C',
      'Size': '55',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '97',
    },
    {
      'Tanggal Restock': '29/03/2026',
      'Kode_Peti': 'A',
      'Size': '80',
      'Inbound': '12.30',
      'Outbound': '14.00',
      'Stok/Kg': '69',
    },
    {
      'Tanggal Restock': '04/04/2026',
      'Kode_Peti': 'A',
      'Size': '35',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '83',
    },
    {
      'Tanggal Restock': '10/04/2026',
      'Kode_Peti': 'A',
      'Size': '60',
      'Inbound': '11.10',
      'Outbound': '13.40',
      'Stok/Kg': '117',
    },
    {
      'Tanggal Restock': '14/04/2026',
      'Kode_Peti': 'A',
      'Size': '35',
      'Inbound': '09.30',
      'Outbound': '11.00',
      'Stok/Kg': '72',
    },
    {
      'Tanggal Restock': '17/04/2026',
      'Kode_Peti': 'A',
      'Size': '35',
      'Inbound': '08.40',
      'Outbound': '11.00',
      'Stok/Kg': '46',
    },
    {
      'Tanggal Restock': '17/04/2026',
      'Kode_Peti': 'B',
      'Size': '55',
      'Inbound': '08.40',
      'Outbound': '11.00',
      'Stok/Kg': '81',
    },
    {
      'Tanggal Restock': '24/04/2026',
      'Kode_Peti': 'A',
      'Size': '20',
      'Inbound': '09.30',
      'Outbound': '11. 00',
      'Stok/Kg': '52',
    },
  ];
    // ================= PESANAN MASUK =================
  static List<Map<String, String>> pesananMasuk = [];
  
    // ================= HISTORY =================
  static List<Map<String, String>> history = [];

  
  // ================= FUNCTION STATUS =================
  static String getStatus(String tanggal, String size) {
    final peti = dataPeti.where((e) =>
      e['Tanggal Restock'] == tanggal &&
      e['Size'] == size
    ).toList();

    return peti.isNotEmpty ? "READY" : "-";
  }

  static void updateStatus() {
  for (var item in hargaUdang) {
    String tanggal = item['Tanggal Update Harga'] ?? "";
    String size = item['Size'] ?? "";

    bool ada = dataPeti.any((p) =>
      p['Tanggal Restock'] == tanggal &&
      p['Size'] == size
    );

    item['Status'] = ada ? "READY" : "-";
  }
}

  // ================= STOK GABUNG =================
  static List<Map<String, String>> getStokGabungan() {
    List<Map<String, String>> result = [];

    for (int i = 0; i < dataPeti.length; i++) {
      final peti = dataPeti[i];

      result.add({
        "No": (i + 1).toString(),
        "Tanggal Restock": peti['Tanggal Restock'] ?? "-",
        "Size": peti['Size'] ?? "-",
        "Kode_Peti": peti['Kode_Peti'] ?? "-",
        "Inbound": peti['Inbound'] ?? "-",
        "Stok/Kg": peti['Stok/Kg'] ?? "-",
        "Outbound": peti['Outbound'] ?? "-",
        "Status": getStatus(
          peti['Tanggal Restock'] ?? "",
          peti['Size'] ?? "",
        ),
      });
    }

    return result;
  }

  // ================= SEMUA DATA =================
  static List<Map<String, String>> getSemuaData() {
    List<Map<String, String>> result = [];

    for (var h in hargaUdang) {
      result.add({
        "jenis": "Harga/Kg",
        "Tanggal Update Harga": h['Tanggal Update Harga'] ?? "-",
        "Size": h['Size'] ?? "-",
        "Harga/Kg": h['Harga/Kg'] ?? "-",
        "Status": "-",
      });
    }

    for (var p in dataPeti) {
      result.add({
        "jenis": "Stok",
        "Tanggal Restock": p['Tanggal Restock'] ?? "-",
        "Size": p['Size'] ?? "-",
        "Kode_Peti": p['Kode_Peti'] ?? "-",
        "Inbound": p['Inbound'] ?? "-",
        "Stok/Kg": p['Stok/Kg'] ?? "-",
        "Outbound": p['Outbound'] ?? "-",
        "Status": getStatus(p['Tanggal Restock'] ?? "", p['Size'] ?? ""),
      });
    }

    return result;
  }
}