// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVRMqSmMkiJ2M8WdJhCwqvkKO_Io8AX-I',
    appId: '1:822157144970:web:aae1209a175154d4fc8e73',
    messagingSenderId: '822157144970',
    projectId: 'aplikasi-db524',
    authDomain: 'aplikasi-db524.firebaseapp.com',
    storageBucket: 'aplikasi-db524.firebasestorage.app',
    measurementId: 'G-3FFN3XGM3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAak0R4WhE4bd4UlEBgjz7Y8SCGetrhUhg',
    appId: '1:822157144970:android:a1e78abe08d4e07efc8e73',
    messagingSenderId: '822157144970',
    projectId: 'aplikasi-db524',
    storageBucket: 'aplikasi-db524.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDULzVTDqcK4KTyvcZE7VizaZMuEBJ3s5w',
    appId: '1:822157144970:ios:b1b444d5c7ad320bfc8e73',
    messagingSenderId: '822157144970',
    projectId: 'aplikasi-db524',
    storageBucket: 'aplikasi-db524.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiSkripsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDULzVTDqcK4KTyvcZE7VizaZMuEBJ3s5w',
    appId: '1:822157144970:ios:b1b444d5c7ad320bfc8e73',
    messagingSenderId: '822157144970',
    projectId: 'aplikasi-db524',
    storageBucket: 'aplikasi-db524.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiSkripsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVRMqSmMkiJ2M8WdJhCwqvkKO_Io8AX-I',
    appId: '1:822157144970:web:04e4937945940e1ffc8e73',
    messagingSenderId: '822157144970',
    projectId: 'aplikasi-db524',
    authDomain: 'aplikasi-db524.firebaseapp.com',
    storageBucket: 'aplikasi-db524.firebasestorage.app',
    measurementId: 'G-BNBSFF4YLG',
  );
}
